In [1]:
import pandas as pd 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
df_customerchurn = pd.read_csv('userchurn.csv')

In [3]:
df_customerchurn

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn,SeniorCitizen,tenure,MonthlyCharges
0,5312,0,1,0,0,1,0,0,0,0,0,0,0,1,2,2484,0,0.0,0.013889,0.115423
1,3919,1,0,0,1,0,0,2,2,0,0,0,1,0,3,1454,0,0.0,0.472222,0.385075
2,2541,1,0,0,1,0,0,2,0,0,0,0,0,1,3,155,1,0.0,0.027778,0.354229
3,5469,1,0,0,0,1,0,2,2,2,0,0,1,0,0,1389,0,0.0,0.625000,0.239303
4,6431,0,0,0,1,0,1,0,0,0,0,0,0,1,2,917,1,0.0,0.027778,0.521891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6957,4832,1,0,0,1,2,1,0,0,0,0,0,0,1,2,5712,1,NaN,NaN,NaN
6958,6794,1,0,0,1,0,1,0,0,0,0,0,0,1,1,2254,0,NaN,NaN,NaN
6959,432,0,0,0,1,2,1,2,2,0,2,0,0,1,1,5370,1,NaN,NaN,NaN
6960,5919,1,0,0,1,0,1,0,0,0,2,0,0,1,0,885,0,NaN,NaN,NaN
6961,5439,0,0,0,0,1,0,0,2,2,2,2,1,0,2,5677,0,NaN,NaN,NaN

In [4]:
df_customerchurn.drop(['customerID'],axis=1,inplace=True)

In [5]:
df_customerchurn.isna()

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn,SeniorCitizen,tenure,MonthlyCharges
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6957,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
6958,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
6959,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
6960,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
6961,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True

In [6]:
df_customerchurn.dropna(inplace=True)

#nan values dropped using dropna

In [7]:
df_customerchurn

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn,SeniorCitizen,tenure,MonthlyCharges
0,0,1,0,0,1,0,0,0,0,0,0,0,1,2,2484,0,0.0,0.013889,0.115423
1,1,0,0,1,0,0,2,2,0,0,0,1,0,3,1454,0,0.0,0.472222,0.385075
2,1,0,0,1,0,0,2,0,0,0,0,0,1,3,155,1,0.0,0.027778,0.354229
3,1,0,0,0,1,0,2,2,2,0,0,1,0,0,1389,0,0.0,0.625000,0.239303
4,0,0,0,1,0,1,0,0,0,0,0,0,1,2,917,1,0.0,0.027778,0.521891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6882,1,0,0,1,0,1,0,0,2,2,0,0,0,2,5806,0,1.0,0.013889,0.572139
6883,0,1,1,1,0,2,1,1,1,1,1,2,1,0,2093,0,0.0,0.527778,0.509950
6884,0,0,0,1,0,1,0,0,0,2,2,1,1,3,2873,0,0.0,0.930556,0.842786
6885,0,1,0,1,2,1,0,2,0,2,0,0,1,2,3328,0,0.0,0.263889,0.601493
6886,0,1,0,1,2,1,0,0,0,0,0,0,1,1,1260,1,0.0,0.166667,0.421891

In [8]:
df_customerchurn.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6882    False
6883    False
6884    False
6885    False
6886    False
Length: 6887, dtype: bool

In [9]:
df_customerchurn.drop_duplicates(inplace=True)
#Duplicates removed

In [10]:
df_customerchurn

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn,SeniorCitizen,tenure,MonthlyCharges
0,0,1,0,0,1,0,0,0,0,0,0,0,1,2,2484,0,0.0,0.013889,0.115423
1,1,0,0,1,0,0,2,2,0,0,0,1,0,3,1454,0,0.0,0.472222,0.385075
2,1,0,0,1,0,0,2,0,0,0,0,0,1,3,155,1,0.0,0.027778,0.354229
3,1,0,0,0,1,0,2,2,2,0,0,1,0,0,1389,0,0.0,0.625000,0.239303
4,0,0,0,1,0,1,0,0,0,0,0,0,1,2,917,1,0.0,0.027778,0.521891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6882,1,0,0,1,0,1,0,0,2,2,0,0,0,2,5806,0,1.0,0.013889,0.572139
6883,0,1,1,1,0,2,1,1,1,1,1,2,1,0,2093,0,0.0,0.527778,0.509950
6884,0,0,0,1,0,1,0,0,0,2,2,1,1,3,2873,0,0.0,0.930556,0.842786
6885,0,1,0,1,2,1,0,2,0,2,0,0,1,2,3328,0,0.0,0.263889,0.601493
6886,0,1,0,1,2,1,0,0,0,0,0,0,1,1,1260,1,0.0,0.166667,0.421891

In [11]:
df_customerchurn.describe()

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn,SeniorCitizen,tenure,MonthlyCharges
count,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000,6887.000000
mean,0.505590,0.483084,0.300131,0.904748,0.937999,0.880209,0.796573,0.905474,0.797735,0.983883,0.995208,0.691738,0.589371,1.577320,3223.948163,0.265137,0.161318,0.449034,0.462160
std,0.500005,0.499750,0.458348,0.293584,0.949229,0.737976,0.859756,0.878426,0.860030,0.883351,0.883485,0.834432,0.491984,1.068424,1868.445277,0.441438,0.367851,0.340939,0.299923
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1595.000000,0.000000,0.000000,0.125000,0.169900
50%,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,2.000000,3218.000000,0.000000,0.000000,0.402778,0.517910
75%,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,4850.500000,1.000000,0.000000,0.763889,0.712438
max,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,3.000000,6459.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
df_customerchurn.corr()

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn,SeniorCitizen,tenure,MonthlyCharges
gender,1.000000,0.000524,0.010738,-0.006265,-0.006766,-0.001137,-0.013738,-0.000615,-0.004969,-0.004235,-0.009309,0.000476,-0.011329,0.014618,-0.006054,-0.008690,-0.006878,0.002228,-0.007204
Partner,0.000524,1.000000,0.452966,0.016731,0.140600,0.003364,0.150677,0.166557,0.125671,0.138369,0.131875,0.295519,-0.016443,-0.154414,0.058349,-0.148186,0.014451,0.018437,0.035792
Dependents,0.010738,0.452966,1.000000,0.000956,-0.026317,0.049634,0.151272,0.078408,0.134129,0.047100,0.020049,0.243459,-0.112849,-0.041315,-0.012951,-0.163673,0.023734,0.030950,0.031470
PhoneService,-0.006265,0.016731,0.000956,1.000000,-0.021195,0.387033,-0.019244,0.001121,-0.019950,0.054557,0.040792,0.002241,0.014707,-0.005222,0.084672,0.012248,0.002454,-0.006976,0.010849
MultipleLines,-0.006766,0.140600,-0.026317,-0.021195,1.000000,-0.110320,0.008210,0.122374,0.012921,0.173906,0.181990,0.112826,0.166261,-0.176911,0.113957,0.037504,-0.001712,0.000337,0.005761
InternetService,-0.001137,0.003364,0.049634,0.387033,-0.110320,1.000000,-0.034064,0.044135,-0.023766,0.109091,0.097792,0.104163,-0.143101,0.085698,-0.055409,-0.051381,-0.004233,0.000959,0.005898
OnlineSecurity,-0.013738,0.150677,0.151272,-0.019244,0.008210,-0.034064,1.000000,0.176245,0.288243,0.044825,0.055881,0.377145,-0.160777,-0.101366,0.044219,-0.293308,-0.010558,0.006943,-0.013668
DeviceProtection,-0.000615,0.166557,0.078408,0.001121,0.122374,0.044135,0.176245,1.000000,0.237847,0.280074,0.287774,0.348365,-0.039759,-0.134644,0.104669,-0.175791,0.004502,-0.004639,0.009628
TechSupport,-0.004969,0.125671,0.134129,-0.019950,0.012921,-0.023766,0.288243,0.237847,1.000000,0.161822,0.160608,0.424067,-0.114293,-0.103012,0.056162,-0.283316,-0.004720,0.024326,-0.003777
StreamingTV,-0.004235,0.138369,0.047100,0.054557,0.173906,0.109091,0.044825,0.280074,0.161822,1.000000,0.434770,0.227514,0.094038,-0.103081,0.137152,-0.034475,0.019176,-0.013216,0.012494
StreamingMovies,-0.009309,0.131875,0.020049,0.040792,0.181990,0.097792,0.055881,0.287774,0.160608,0.434770,1.000000,0.229065,0.084679,-0.109993,0.144960,-0.036212,0.009975,0.002685,0.026336
Contract,0.000476,0.295519,0.243459,0.002241,0.112826,0.104163,0.377145,0.348365,0.424067,0.227514,0.229065,1.000000,-0.176436,-0.225825,0.104886,-0.396661,-0.002612,0.025322,0.006336
PaperlessBilling,-0.011329,-0.016443,-0.112849,0.014707,0.166261,-0.143101,-0.160777,-0.039759,-0.114293,0.094038,0.084679,-0.176436,1.000000,-0.063913,0.103568,0.191780,-0.001438,-0.006799,-0.014654
PaymentMethod,0.014618,-0.154414,-0.041315,-0.005222,-0.176911,0.085698,-0.101366,-0.134644,-0.103012,-0.103081,-0.109993,-0.225825,-0.063913,1.000000,-0.068172,0.105863,-0.022319,0.014064,-0.001680
TotalCharges,-0.006054,0.058349,-0.012951,0.084672,0.113957,-0.055409,0.044219,0.104669,0.056162,0.137152,0.144960,0.104886,0.103568,-0.068172,1.000000,0.016516,0.018920,0.001175,0.001578
Churn,-0.008690,-0.148186,-0.163673,0.012248,0.037504,-0.051381,-0.293308,-0.175791,-0.283316,-0.034475,-0.036212,-0.396661,0.191780,0.105863,0.016516,1.000000,0.016485,-0.009266,0.001441
SeniorCitizen,-0.006878,0.014451,0.023734,0.002454,-0.001712,-0.004233,-0.010558,0.004502,-0.004720,0.019176,0.009975,-0.002612,-0.001438,-0.022319,0.018920,0.016485,1.000000,0.017109,0.219299
tenure,0.002228,0.018437,0.030950,-0.006976,0.000337,0.000959,0.006943,-0.004639,0.024326,-0.013216,0.002685,0.025322,-0.006799,0.014064,0.001175,-0.009266,0.017109,1.000000,0.247534
MonthlyCharges,-0.007204,0.035792,0.031470,0.010849,0.005761,0.005898,-0.013668,0.009628,-0.003777,0.012494,0.026336,0.006336,-0.014654,-0.001680,0.001578,0.001441,0.219299,0.247534,1.000000

In [13]:
## y is dependent variable and X is independent variable.
# Load X Variables into a Pandas Dataframe with columns 
y=df_customerchurn['Churn']
X=df_customerchurn.drop(['Churn'],axis=1)
print(y.shape)
print(X.shape)

(6887,)
(6887, 18)

In [14]:
print(X.columns)

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'TotalCharges', 'SeniorCitizen', 'tenure',
       'MonthlyCharges'],
      dtype='object')

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

#1a Split the data into test and  training and testing

In [16]:
DC=DecisionTreeClassifier()
#1b build the model
DC=DC.fit(X_train,y_train)
y_pred=DC.predict(X_test)

#1c make Predictions

In [17]:
print("Actual Values:")
print(y_test)
print("Predicted values:")
print(y_pred)

Actual Values:
3243    0
927     0
413     0
1915    0
5459    0
       ..
3660    0
6410    0
2641    0
5795    0
3762    0
Name: Churn, Length: 1378, dtype: int64
Predicted values:
[0 0 0 ... 0 0 1]

In [18]:
d2=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
d2.head(30)

#actual and predicted dataframe

      Actual  Predicted
3243       0          0
927        0          0
413        0          0
1915       0          0
5459       0          0
4462       0          0
2196       1          0
2167       1          1
368        1          1
2076       1          0
1502       1          1
2296       0          0
6874       0          0
5240       0          0
2529       0          0
4678       0          1
3934       0          1
1217       0          0
6037       0          0
2174       0          1
5729       1          1
2619       1          1
5342       0          0
5369       1          1
1373       0          0
6141       0          0
2894       0          0
6870       1          0
6336       0          1
961        0          0

In [19]:
print("accuracy",metrics.accuracy_score(y_test,y_pred))

#accuracy for knn:0.7518, acccuracy for SVC:0.7808, accuracy for RandomForest:0.7743, 
#accuracy for Decisiontreeclassifier:0.7213, accuracy for logisticregression:0.7837

#Logistic regression had the best accuracy of 0.7837

accuracy 0.7213352685050798

In [20]:
cf=confusion_matrix(y_test,y_pred)
#confusion matrix

In [21]:
print(cf)
#print confusion matrix#

[[776 209]
 [175 218]]

In [22]:
print(classification_report(y_test,y_pred))
#classification report#
#1d Evaluate model using appropriate evaluation metrics

              precision    recall  f1-score   support

           0       0.82      0.79      0.80       985
           1       0.51      0.55      0.53       393

    accuracy                           0.72      1378
   macro avg       0.66      0.67      0.67      1378
weighted avg       0.73      0.72      0.72      1378

In [23]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

clf = DecisionTreeClassifier(random_state=1)

params =  {
    'criterion' : ['gini', 'entropy'],
    'min_samples_leaf': [1, 2, 3],
    'max_depth': [1, 2, 3]
}
#
# Create gridsearch instance
#
grid = GridSearchCV(estimator=clf,param_grid=params,cv=10)
                    

grid.fit(X_train, y_train)
#
grid.best_score_, grid.best_params_

#grid best score: 0.7752
#grid best parameter: Criterion:gini, max_depth:3, Minimum sample leaf:1


#2a model built
#2b gridsearchcv used for parameter hypertuning

(0.7752809767365121,
 {'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 1})

In [25]:
import pandas as pd

# Create a dictionary

data =  {'Model_name': ['DecisionTreeClassifier'],

        'Best_Score': [0.7752],

        'Best_Parameters': ['Criterion: Gini', 'Max_Depth:3', 'Min_Samples_leaf:1' ]}

In [26]:
data

{'Model_name': ['DecisionTreeClassifier'],
 'Best_Score': [0.7752],
 'Best_Parameters': ['Criterion: Gini', 'Max_Depth:3', 'Min_Samples_leaf:1']}

In [27]:
df = pd.DataFrame(list(data.items()), columns=['Key', 'Value'])

In [28]:
df

#Create a dataframe to store the result of GridSearchCV for all the models which
#will includes model_name, best_score_ and best_params_

               Key                                              Value
0       Model_name                           [DecisionTreeClassifier]
1       Best_Score                                           [0.7752]
2  Best_Parameters  [Criterion: Gini, Max_Depth:3, Min_Samples_lea...

In [ ]:
#3 Observations and conclusions made from this project

#This project is a classification problem of customer churn in which the dependent variabele y is churn. From the observations made,
#Logistic regression has the highest accuracy(0.7837) and also the best score(0.7756) which makes it a perfect fit for this capstone project.